name: api call cron

on:
  schedule:
    - cron: "0 16 * * *" # UTC 기준으로 매일 16시 -> 한국 시간 새벽 1시

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute collect_data.py script
        run: python collect_data/collect_data.py
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER_NAME: ${{ secrets.DB_USER_NAME }}
          DB_USER_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
